### ISSUE TITLE
issues with chromedriver.exe

### ISSUE THREAD

**Issue by emilianosalatino** [visheshdvivedi/Whatsapp-Automation-Python#1]
I cannot for the love of the lord get chromedriver.exe to load anywhere.

Tried putting in path, probably copied it into every folder i know, yet, i can't get the script to work because it says chromedriver.exe has to be on PATH. 

Any ideas?

**Comment by itsallaboutpython** [comment]
Hi @emilianosalatino,

As long as the 'main.py' and 'chromedriver.exe' exist on the same path, there shouldn't be any problems. If the problem still exists, provide more information like where is 'main.py' and 'chromedriver.exe' are present and the error message
